config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    get "signup", to: "users#new"
    get "login" , to: "sessions#new"
    post "login" , to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    resources :users
    resources :sessions
    resources :categories, only: :show
  end

  namespace :admin do
    root "home#index"

    resources :categories, except: :show
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products

	def self.options_for_select
		all.map do |category|
			[category.name, category.id]
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: {user: 0, admin: 1}
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                     format:     { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
	include SessionsHelper

	layout "admin"

	before_action :check_admin

	def check_admin
		if current_user.blank? || current_user.user?
			redirect_to root_url
		end
	end		
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
	before_action :set_categories, only: [:edit, :update, :destroy]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new params_categories
		if @category.save
			redirect_to admin_categories_path
		else
			render :new
		end
	end

	def edit; end

	def update
		if @category.update params_categories
			redirect_to admin_categories_path
		else
			render :edit
		end
	end

	def destroy
		@category.destroy!
		redirect_to admin_categories_path
	end

	private

	def set_categories
		@category = Category.find_by id: params[:id]
	end

	def params_categories
		params.require(:category).permit :name
	end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController
	def index
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
	before_action :set_products, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def show;	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new params_products
		if @product.save
			redirect_to admin_product_path(@product)
		else
			render :new
		end
	end

	def edit; end

	def update
		if @product.update params_products
			redirect_to admin_product_path(@product)
		else
			render :edit
		end
	end

	def destroy
		@product.destroy!
		redirect_to admin_products_path
	end

	private

	def set_products
		@product = Product.find_by id: params[:id]
	end

	def params_products
		params.require(:product).permit :name, :price, :quantity, :description, :image, :category_id
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :set_locale, :set_category

  private

  def set_category
    @categories = Category.all
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@products = Product.where(category_id: params[:id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by email: params[:session][:email].downcase
    if @user&.authenticate(params[:session][:password])
      log_in @user
      redirect_to root_url
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
    redirect_to root_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :email, :password, :password_confirmation, :name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    session[:user_id].present?
  end

  def log_out
    session.delete :user_id
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for category, url: url , method: method do |f| %>
  Name: <%= f.text_field :name %><br />
  <%= f.submit %>
<% end %>

app/views/admin/categories/edit.html.erb
<p>Edit Category</p>

<%= render "form", category: @category, url: admin_category_path(@category), method: :patch %>

app/views/admin/categories/index.html.erb
<h2>List Category</h2>
<%= link_to "<button>New</button>".html_safe, new_admin_category_path %>
<table style="width:100%">
	<tr>
		<th>id</th>
		<th>Name</th>
		<th>Action</th>
	</tr>
	<% @categories.map do |category| %>
		<tr>
			<td><%= category.id %></td>
			<td><%= category.name %></td>
			<td>
				<%= link_to "<button class='btn btn-info'>Edit</button>".html_safe, edit_admin_category_path(category) %>
				<%= link_to "<button class='btn btn-danger'>Delete</button>".html_safe, admin_category_path(category), method: :delete %>
			</td>
		</tr>
	<% end %>
</table>
<style>
table {
	margin-top: 10px;
}
th, td {
  border:1px solid black;
}
</style>

app/views/admin/categories/new.html.erb
<p>Tao moi Category</p>

<%= render "form", category: @category, url: admin_categories_path(@category), method: :post %>

app/views/admin/products/_form.html.erb
<%= form_for product, url: url , method: method do |f| %>
  Name: <%= f.text_field :name, class: "form-control" %><br />
  Price: <%= f.text_field :price, class: "form-control" %><br />
  Quantity: <%= f.text_field :quantity, class: "form-control" %><br />
  Category: <%= f.select :category_id, Category.options_for_select %><br />
  Description: <%= f.text_field :description, class: "form-control" %><br />
  Image: <%= f.text_field :image, class: "form-control" %><br />
  <%= f.submit %>
<% end %>

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>

<%= render "form", product: @product, url: admin_product_path(@product), method: :patch %>

app/views/admin/products/index.html.erb
<h2>List Products</h2>
<%= link_to "<button>New</button>".html_safe, new_admin_product_path %>
<table style="width:100%">
	<tr>
		<th>id</th>
		<th>Name</th>
		<th>Action</th>
	</tr>
	<% @products.map do |product| %>
		<tr>
			<td><%= product.id %></td>
			<td><%= product.name %></td>
			<td>
				<%= link_to "<button class='btn btn-success'>View</button>".html_safe, admin_product_path(product) %>
				<%= link_to "<button class='btn btn-info'>Edit</button>".html_safe, edit_admin_product_path(product) %>
				<%= link_to "<button class='btn btn-danger'>Delete</button>".html_safe, admin_product_path(product), method: :delete %>
			</td>
		</tr>
	<% end %>
</table>
<style>
table {
	margin-top: 10px;
}
th, td {
  border:1px solid black;
}
</style>

app/views/admin/products/new.html.erb
<p>Tao moi Product</p>

<%= render "form", product: @product, url: admin_products_path(@product), method: :post %>

app/views/admin/products/show.html.erb
<p> ID: <%= @product.id %></p>
<p> Name: <%= @product.name %></p>
<p> Price: <%= @product.price %></p>
<p> Quantity: <%= @product.quantity %></p>
<p> Description: <%= @product.description %></p>
<p> Image: <%= @product.image %></p>
<p> Category_id: <%= @product.category_id %></p>

app/views/categories/show.html.erb
<div id="list-products" class="col-sm-12">
    <h3>Sản Phẩm</h3>
</div>
<div class="block-product">
    <div class="block-category">
        <h3>Category</h3>
        <div class="list-category">
            <ul>
            <% @categories.each do |category| %>
                <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
            </ul>
        </div>
    </div>

    <div class="main-product">  
        <div class="row">
            <% @products.each do |product| %>
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="box">
                        <div class="content">
                            <img src="https://storage.f5fruitshop.vn/product/1600832552121autum-uc-3.jpg" alt="Avatar" style="width:100%">
                            <h3><%= product.name %></h3>    
                            <div class="d-flex justify-content-around align-items-center">
                            <div class="price"><%= product.price %><sup>đ</sup></div>   
                            </div>
                            <a href="#">Buy Now</a>
                        </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div id="list-products" class="col-sm-12">
    <h3>Sản Phẩm</h3>
</div>
<div class="block-product">
    <div class="block-category">
        <h3>Category</h3>
        <div class="list-category">
            <ul>
            <li><a href="#">Mango</a></li>
            <li><a href="#">Apple</a></li>
            <li><a href="#">Grape</a></li>
            <li><a href="#">Plum</a></li>
            <li><a href="#">Durian</a></li>
            <li><a href="#">Gusduss</a></li>
            </ul>
        </div>
    </div>

    <div class="main-product">  
        <div class="row">
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="box">
                    <div class="content">
                        <img src="https://storage.f5fruitshop.vn/product/1600832552121autum-uc-3.jpg" alt="Avatar" style="width:100%">
                        <h3>Nho Ngón Tay Mỹ</h3>
                        <div class="d-flex justify-content-around align-items-center">
                        <div class="price">249.000<sup>đ</sup></div>
                        <div class="old-price">303.450<sup>đ</sup></div>
                        </div>
                        <a href="#">Buy Now</a>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                <div class="box">
                    <div class="content">
                    <img src="https://storage.f5fruitshop.vn/product/1583459854130nhodennp.jpg" alt="Avatar" style="width:100%">
                    <h3>Nho Ngón Tay Mỹ</h3>
                    <div class="d-flex justify-content-around align-items-center">
                        <div class="price">249.000<sup>đ</sup></div>
                        <div class="old-price">303.450<sup>đ</sup></div>
                    </div>
                    <a href="#">Buy Now</a>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="box">
                    <div class="content">
                        <img src="https://storage.f5fruitshop.vn/product/1599014261158le-np-0k.jpg" alt="Avatar" style="width:100%">
                        <h3>Nho Ngón Tay Mỹ</h3>
                        <div class="d-flex justify-content-around align-items-center">
                        <div class="price">249.000<sup>đ</sup></div>
                        <div class="old-price">303.450<sup>đ</sup></div>
                        </div>
                        <a href="#">Buy Now</a>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="box">
                        <div class="content">
                        <img src="https://storage.f5fruitshop.vn/product/1577349312584envymy.jpg" alt="Avatar" style="width:100%">
                        <h3>Nho Ngón Tay Mỹ</h3>
                        <div class="d-flex justify-content-around align-items-center">
                            <div class="price">249.000<sup>đ</sup></div>
                            <div class="old-price">303.450<sup>đ</sup></div>
                        </div>
                        <a href="#">Buy Now</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="box">
                    <div class="content">
                        <img src="https://storage.f5fruitshop.vn/product/1600832552121autum-uc-3.jpg" alt="Avatar" style="width:100%">
                        <h3>Nho Ngón Tay Mỹ</h3>
                        <div class="d-flex justify-content-around align-items-center">
                        <div class="price">249.000<sup>đ</sup></div>
                        <div class="old-price">303.450<sup>đ</sup></div>
                        </div>
                        <a href="#">Buy Now</a>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                <div class="box">
                    <div class="content">
                    <img src="https://storage.f5fruitshop.vn/product/1583459854130nhodennp.jpg" alt="Avatar" style="width:100%">
                    <h3>Nho Ngón Tay Mỹ</h3>
                    <div class="d-flex justify-content-around align-items-center">
                        <div class="price">249.000<sup>đ</sup></div>
                        <div class="old-price">303.450<sup>đ</sup></div>
                    </div>
                    <a href="#">Buy Now</a>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="box">
                    <div class="content">
                        <img src="https://storage.f5fruitshop.vn/product/1599014261158le-np-0k.jpg" alt="Avatar" style="width:100%">
                        <h3>Nho Ngón Tay Mỹ</h3>
                        <div class="d-flex justify-content-around align-items-center">
                        <div class="price">249.000<sup>đ</sup></div>
                        <div class="old-price">303.450<sup>đ</sup></div>
                        </div>
                        <a href="#">Buy Now</a>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="box">
                        <div class="content">
                        <img src="https://storage.f5fruitshop.vn/product/1577349312584envymy.jpg" alt="Avatar" style="width:100%">
                        <h3>Nho Ngón Tay Mỹ</h3>
                        <div class="d-flex justify-content-around align-items-center">
                            <div class="price">249.000<sup>đ</sup></div>
                            <div class="old-price">303.450<sup>đ</sup></div>
                        </div>
                        <a href="#">Buy Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_banner.html.erb
<div class="block-carousel">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="https://firebasestorage.googleapis.com/v0/b/f5fruitprod.appspot.com/o/banner_images%2F1648606622575_NaN.jpg?alt=media&token=a6f3b785-0897-42e4-bbcd-de4736ae0a0f" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://firebasestorage.googleapis.com/v0/b/f5fruitprod.appspot.com/o/banner_images%2F1590747458436_%5Bobject%20File%5D?alt=media&token=1f3bc75f-7a63-42f9-ad12-c9685206bbdb" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://firebasestorage.googleapis.com/v0/b/f5fruitprod.appspot.com/o/banner_images%2F1626755131829_NaN.png?alt=media&token=96569e6c-b87b-456c-8d77-fc730dcdbb5c" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
      <h3 class="copy-right">
        © 2022 Hệ thống hoa quả sạch Fuji Fruit   
      </h3>
</div>

app/views/layouts/_header-top.html.erb
<div class="header_top d-flex">
  <div class="header_top_left">
    <li class="nav-item active">
      <a class="nav-link font_family" href="tel:0901966516">Hotline: 0901966516<span class="sr-only">(current)</span></a>
    </li>
  </div>
  <div class="header_top_right">
    <ul class="d-flex">
      <div class="dropdown d-flex align-items-center">
        <a class="dropdown-toggle nav-link font_family" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tiếng Việt 
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item nav-link-line font_family" href="#">English</a>
          <a class="dropdown-item nav-link-line font_family" href="#">Japan</a>
        </div>
      </div>
      <form class="form-inline my-2 my-lg-0 font_family">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t(".profile"), current_user , class: "dropdown-item" %></li>
                <li><%= link_to t(".settings"), edit_user_path(current_user), class: "dropdown-item" %></li>
                <li><% if current_user.admin? %>
                    <%= link_to "Manager", admin_root_path , class: "dropdown-item" %>
                    <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to t(".logout"), logout_path, method: :delete , class: "dropdown-item" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t(".login"), login_path %></li>
            <li class="nav-link">|</li>
            <li><%= link_to t(".signup"), signup_path %></li>
          <% end %>
      </form>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-nav navbar-light">
  <a class="navbar-brand" href="#"><i class="fa-solid fa-house-chimney"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">PRODUCT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CONTACT</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <div class="btn-cart"><a href="#"><i class="fa-solid fa-cart-shopping"></i></a></div>
    </form>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<head>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body id="body-pd">
  <header class="header" id="header">
      <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
      <div class="header_img"> <img src="https://i.imgur.com/hczKIze.jpg" alt=""> </div>
  </header>
  <div class="l-navbar" id="nav-bar">
      <nav class="nav">
    		<div>
	        <a href="#" class="nav_logo"> <i class="bx bx-layer nav_logo-icon"></i> <span class="nav_logo-name">Admin</span> </a>
	        <div class="nav_list">
					  <a href="#" class="nav_link active">
					    <i class="bx bx-grid-alt nav_icon"></i>
					    <span class="nav_name">Dashboard</span>
					  </a>
					  <a href="#" class="nav_link">
					    <i class="bx bx-user nav_icon"></i>
					    <span class="nav_name">Users</span>
					  </a>
					  <%= link_to "<i class='bx bx-message-square-detail nav_icon'></i>
					    <span class='nav_name'>Category</span>".html_safe, admin_categories_path, class: "nav_link" %>
					  <%= link_to "<i class='bx bx-bookmark nav_icon'></i>
					    <span class='nav_name'>Product</span>".html_safe, admin_products_path, class: "nav_link" %>
					  <a href="#" class="nav_link">
					    <i class="bx bx-folder nav_icon"></i>
					    <span class="nav_name">Cart</span>
					  </a>
					  <a href="#" class="nav_link">
					    <i class="bx bx-bar-chart-alt-2 nav_icon"></i>
					    <span class="nav_name">Stats</span>
					  </a>
					</div>
    		</div>
    			<a href="#" class="nav_link"> <i class="bx bx-log-out nav_icon"></i> <span class="nav_name">SignOut</span> </a>
			</nav>
  </div>  
</body>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinhGreenFruit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/sidebar" %>
    <div class="height-100 bg-light mt-65">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinhGreenFruit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bg-nav">
      <div class="container">
      <%= render "layouts/header-top" %>
      </div>
    </div>
    
    <div class="border-bot"></div>
    <div class="bg-nav">
      <div class="container">
      <%= render "layouts/header" %>
      </div>
    </div>
    <%= render "layouts/banner" %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class="d-flex justify-content-center mt-40">Sign up</h1>

<div class="d-flex justify-content-center">
  <div class="col-md-6">
    <%= form_for(@user) do |f| %>
    	<%= render "shared/error_messages", object: @user %>
      <div class="form-group">
        <%= f.label :name %>
      	<%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
      	<%= f.label :email %>
      	<%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
      	<%= f.label :password %>
      	<%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
      	<%= f.label :password_confirmation, "Confirmation" %>
      	<%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
	  <aside class="col-md-4">
	    <section class="user_info">
	      <h1 class="mt-40">
	        <%= @user.name %>
	      </h1>
	    </section>
	  </aside>
	</div>
</div>